# Generated by Django 5.1.3 on 2024-11-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_category_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="owner",
        ),
    ]
